# Generated by Django 3.2 on 2021-08-15 15:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pasien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=50)),
                ('TanggalLahir', models.DateField()),
                ('NomorHandphone', models.IntegerField()),
                ('TesCovid', models.BooleanField()),
                ('Demam', models.BooleanField()),
                ('RiwayatMobilisasi', models.BooleanField()),
                ('RiwayatKontak', models.BooleanField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
