# Generated by Django 3.2 on 2021-08-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0002_auto_20210817_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasien',
            name='geom',
        ),
        migrations.AddField(
            model_name='pasien',
            name='bernafas',
            field=models.BooleanField(default='false'),
        ),
        migrations.AddField(
            model_name='pasien',
            name='demam',
            field=models.BooleanField(default='false'),
        ),
        migrations.AddField(
            model_name='pasien',
            name='kontak',
            field=models.BooleanField(default='false'),
        ),
        migrations.AddField(
            model_name='pasien',
            name='lamaPenyakit',
            field=models.BooleanField(default='false'),
        ),
        migrations.AddField(
            model_name='pasien',
            name='latitude',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pasien',
            name='longitude',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pasien',
            name='nama',
            field=models.CharField(default='sandy', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pasien',
            name='nomorHp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pasien',
            name='pilek',
            field=models.BooleanField(default='false'),
        ),
        migrations.AddField(
            model_name='pasien',
            name='tempatLahir',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pasien',
            name='tenggorokan',
            field=models.BooleanField(default='false'),
        ),
        migrations.AddField(
            model_name='pasien',
            name='tesCovid',
            field=models.BooleanField(default='false'),
        ),
        migrations.AddField(
            model_name='pasien',
            name='tinggal',
            field=models.BooleanField(default='false'),
        ),
    ]
