# Generated by Django 3.2 on 2021-08-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0004_auto_20210820_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasien',
            name='bernafas',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='demam',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='kontak',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='lamaPenyakit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='pilek',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='tenggorokan',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='tesCovid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='tinggal',
            field=models.BooleanField(default=False),
        ),
    ]
