# Generated by Django 3.2 on 2021-08-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0005_auto_20210820_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasien',
            name='latitude',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='longitude',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
