# Generated by Django 3.2 on 2021-08-20 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0008_auto_20210820_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasien',
            name='bernafas',
        ),
        migrations.RemoveField(
            model_name='pasien',
            name='demam',
        ),
        migrations.RemoveField(
            model_name='pasien',
            name='kontak',
        ),
        migrations.RemoveField(
            model_name='pasien',
            name='lamaPenyakit',
        ),
        migrations.RemoveField(
            model_name='pasien',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='pasien',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='pasien',
            name='pilek',
        ),
        migrations.RemoveField(
            model_name='pasien',
            name='tenggorokan',
        ),
        migrations.RemoveField(
            model_name='pasien',
            name='tesCovid',
        ),
        migrations.RemoveField(
            model_name='pasien',
            name='tinggal',
        ),
    ]
