# Generated by Django 3.2 on 2021-08-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0011_auto_20210820_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daftarcovid',
            name='tempatLahir',
        ),
        migrations.AddField(
            model_name='daftarcovid',
            name='usia',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
