# Generated by Django 3.2 on 2021-08-21 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0012_auto_20210820_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daftarcovid',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='daftarcovid',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
