# Generated by Django 3.2 on 2021-08-23 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0013_auto_20210821_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daftarcovid',
            name='nomorHp',
            field=models.BigIntegerField(),
        ),
    ]
