# Generated by Django 3.2 on 2021-08-07 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investarisasi', '0004_alter_investarisasi_pemilik'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investarisasi',
            name='pemilik',
        ),
    ]
