# Generated by Django 3.2 on 2021-08-07 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investarisasi', '0007_alter_investarisasi_pemilik'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pemilik',
        ),
    ]
