# Generated by Django 3.2 on 2021-08-07 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investarisasi', '0008_delete_pemilik'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Investarisasi',
        ),
    ]
