# Generated by Django 3.2 on 2021-08-07 06:56

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investarisasi', '0009_delete_investarisasi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investarisasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(max_length=50)),
                ('luas', models.FloatField()),
                ('pemilik', models.CharField(max_length=50)),
                ('note', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Pemilik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pemilik', models.CharField(max_length=80)),
            ],
        ),
    ]
