# Generated by Django 3.2 on 2021-08-11 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investarisasi', '0014_hutan_lahankosong_semakbelukar_tambak'),
    ]

    operations = [
        migrations.AddField(
            model_name='hutan',
            name='jenis',
            field=models.CharField(default='Hutan', max_length=20),
        ),
        migrations.AddField(
            model_name='kebun',
            name='jenis',
            field=models.CharField(default='Kebun', max_length=20),
        ),
        migrations.AddField(
            model_name='lahankosong',
            name='jenis',
            field=models.CharField(default='Lahan Kosong', max_length=20),
        ),
        migrations.AddField(
            model_name='sawah',
            name='jenis',
            field=models.CharField(default='Sawah', max_length=20),
        ),
        migrations.AddField(
            model_name='semakbelukar',
            name='jenis',
            field=models.CharField(default='Semak Belukar', max_length=20),
        ),
        migrations.AddField(
            model_name='tambak',
            name='jenis',
            field=models.CharField(default='Tambak', max_length=20),
        ),
        migrations.AlterField(
            model_name='hutan',
            name='pemilik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investarisasi.pemilik'),
        ),
        migrations.AlterField(
            model_name='kebun',
            name='pemilik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investarisasi.pemilik'),
        ),
        migrations.AlterField(
            model_name='lahankosong',
            name='pemilik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investarisasi.pemilik'),
        ),
        migrations.AlterField(
            model_name='sawah',
            name='pemilik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investarisasi.pemilik'),
        ),
        migrations.AlterField(
            model_name='semakbelukar',
            name='pemilik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investarisasi.pemilik'),
        ),
        migrations.AlterField(
            model_name='tambak',
            name='pemilik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investarisasi.pemilik'),
        ),
    ]
