# Generated by Django 3.2 on 2021-08-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investarisasi', '0015_auto_20210811_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hutan',
            name='jenis',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='kebun',
            name='jenis',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='lahankosong',
            name='jenis',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sawah',
            name='jenis',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='semakbelukar',
            name='jenis',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tambak',
            name='jenis',
            field=models.CharField(max_length=20),
        ),
    ]
