# Generated by Django 3.2 on 2021-08-11 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investarisasi', '0016_auto_20210811_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investarisasi',
            name='pemilik',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='investarisasi.pemilik'),
        ),
        migrations.AlterField(
            model_name='kebun',
            name='pemilik',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='investarisasi.pemilik'),
        ),
        migrations.AlterField(
            model_name='lahankosong',
            name='pemilik',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='investarisasi.pemilik'),
        ),
        migrations.AlterField(
            model_name='sawah',
            name='pemilik',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='investarisasi.pemilik'),
        ),
        migrations.AlterField(
            model_name='semakbelukar',
            name='pemilik',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='investarisasi.pemilik'),
        ),
        migrations.AlterField(
            model_name='tambak',
            name='pemilik',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='investarisasi.pemilik'),
        ),
    ]
