# Generated by Django 3.2 on 2021-08-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investarisasi', '0018_auto_20210811_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hutan',
            name='pemilik',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='investarisasi',
            name='pemilik',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='kebun',
            name='pemilik',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lahankosong',
            name='pemilik',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sawah',
            name='pemilik',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='semakbelukar',
            name='pemilik',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tambak',
            name='pemilik',
            field=models.CharField(max_length=50),
        ),
    ]
