# Generated by Django 3.2 on 2021-08-12 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investarisasi', '0021_jenislahan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hutan',
            name='jenis',
            field=models.ForeignKey(blank=True, default='6', null=True, on_delete=django.db.models.deletion.CASCADE, to='investarisasi.jenislahan'),
        ),
        migrations.AlterField(
            model_name='kebun',
            name='jenis',
            field=models.ForeignKey(blank=True, default='2', null=True, on_delete=django.db.models.deletion.CASCADE, to='investarisasi.jenislahan'),
        ),
        migrations.AlterField(
            model_name='lahankosong',
            name='jenis',
            field=models.ForeignKey(blank=True, default='5', null=True, on_delete=django.db.models.deletion.CASCADE, to='investarisasi.jenislahan'),
        ),
        migrations.AlterField(
            model_name='sawah',
            name='jenis',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='investarisasi.jenislahan'),
        ),
        migrations.AlterField(
            model_name='semakbelukar',
            name='jenis',
            field=models.ForeignKey(blank=True, default='3', null=True, on_delete=django.db.models.deletion.CASCADE, to='investarisasi.jenislahan'),
        ),
        migrations.AlterField(
            model_name='tambak',
            name='jenis',
            field=models.ForeignKey(blank=True, default='4', null=True, on_delete=django.db.models.deletion.CASCADE, to='investarisasi.jenislahan'),
        ),
    ]
