# Generated by Django 3.2 on 2021-08-14 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investarisasi', '0023_bangunan_lainnya_sungai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lainnya',
            name='jenis',
        ),
        migrations.RemoveField(
            model_name='lainnya',
            name='pemilik',
        ),
        migrations.DeleteModel(
            name='Bangunan',
        ),
        migrations.DeleteModel(
            name='Lainnya',
        ),
    ]
