# Generated by Django 3.2 on 2021-08-14 17:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investarisasi', '0024_auto_20210815_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lainnya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('luas', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('jenis', models.ForeignKey(blank=True, default='9', null=True, on_delete=django.db.models.deletion.CASCADE, to='investarisasi.jenislahan')),
                ('pemilik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investarisasi.pemilik')),
            ],
        ),
    ]
