# Generated by Django 3.2 on 2021-08-15 04:38

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investarisasi', '0027_alter_jalan_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batasdesa',
            name='geom',
            field=django.contrib.gis.db.models.fields.LineStringField(srid=4326),
        ),
        migrations.AlterField(
            model_name='jalan',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
